### ISSUE TITLE
0.91.47 Printing stops without beeing finished

### ISSUE THREAD

**Issue by sapier** [RF1000/Repetier-Firmware#3]
Sometimes printing is aborted without beeing finished, extruder as well as bed is still heated and print object is not driven to output position.

**Comment by RF1000** [comment]
Hello sapier,

do you have more information about this issue in the meanwhile? Did this happen also with newer versions of the firmware?

**Comment by RF1000** [comment]
I close this issue because there is no new information for longer than 6 months.
