### ISSUE TITLE
0.91.48 Printer drives up till z-end switch is bricked

### ISSUE THREAD

**Issue by sapier** [RF1000/Repetier-Firmware#4]
I know there's a known situation where this happens in relation to "stop printing" but there's at leas another way to trigger it.

I did mutliple prints without turning off the rf1000 as everything seemed to work without any issues I didn't stay while bed was preheating. When I came back extruder was running in air with bed behind and way above extruder nozzle. luckyly only front edge of bed was  damaged a little bit.
Looking at z-end switch showed it's been pushed up very hard. I foundmetal cap as well as plastik button somewhere next to the printer. I guess there are some other parts somewhere else in the room.
The Metal cap shows the skrew head so it's been drive up with quite some force.

**Comment by RF1000** [comment]
Hello sapier,

did you experience anything like this again since you have opened this issue?

**Comment by RF1000** [comment]
I close this issue because there is no new information for longer than 6 months.
